### PR TITLE
typo in Psr7ServerRequest

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by Maks3w** [comment]
There is another occurrence in the first lines.

**Comment by harikt** [comment]
@Maks3w not sure I understand.

**Comment by weierophinney** [comment]
@harikt In the second paragraph of the page:

> To convert from a PSR-7 instance to a zend-http instance, use Zend\Psr7Bridge\PsrServerRequest::toZend(). This method takes up to two arguments:

**Comment by harikt** [comment]
@weierophinney so you were looking for `true` to be passed ?

**Comment by weierophinney** [comment]
@harikt The class name is wrong in there; needs to be `Psr7ServerRequest`. I can fix it on merge.

**Comment by harikt** [comment]
Feel free to change / modify. I still didn't get. Sorry about it.

**Pull request closed without merging**
