### PR TITLE
Fix erroneous upload handling

### PR DESCRIPTION
**Pull request by Pittiplatsch**
Second try, now with unit test, and target "develop": Fix https://github.com/zendframework/zend-psr7bridge/issues/21.

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you rebase so only your commits shows in this PR, you can do with the following steps:

1. Ensure the upstream/origin set
```
git remote add upstream https://github.com/zendframework/zend-psr7bridge.git
git remote add origin https://github.com/Pittiplatsch/zend-psr7bridge 
```

2. Process rebase
```
git checkout develop && git pull upstream develop
git checkout fix_erroneous_upload_handling && git rebase develop
git push --force origin fix_erroneous_upload_handling
```

**Comment by Pittiplatsch** [comment]
Done.
Thx for detailed instructions 👍

**Comment by ezimuel** [comment]
@Pittiplatsch thanks for your contribution!

**Comment by Pittiplatsch** [comment]
You're welcome :-)

**Pull request merged**
